events {}
http {
    include mime.types;
    server {
        listen 80;
        server_name sshparser.kotimme.cc;
        location / {
            root /usr/share/nginx/html/sshparser;
            index index.html;
        }
        server_tokens off;
    }
    server {
        listen 80;
        server_name lets-go.kotimme.cc;
        location / {
            root /usr/share/nginx/html/lets-go;
            index index.html;
        }
        server_tokens off;
    }
    server {
        listen 80;
        server_name lets-go-further.kotimme.cc;
        location / {
            root /usr/share/nginx/html/lets-go-further;
            index index.html;
        }
        server_tokens off;
    }
    server {
        listen 80;
        server_name localhost;

        location /in-YleRadio1/128/variant.m3u8 {
            proxy_pass https://yleradiolive.akamaized.net/hls/live/2027672/in-YleRadio1/128/variant.m3u8;
        }
    }
}
