events {}
http {
    include mime.types;
    server {
        listen 80;
        location /radio/YleRadio1Hifi/ {
            proxy_pass https://icecast.live.yle.fi/radio/YleRadio1Hifi/;
            proxy_ssl_verify off;
        }
    }
    server {
        listen 80;
        location /radio/test/ {
            proxy_pass https://www.google.com/;
            proxy_ssl_verify off;
        }
    }
    server {
        listen 80;
        server_name sshparser.kotimme.cc;
        location / {
            root /usr/share/nginx/html/sshparser;
            index index.html;
        }
        server_tokens off;
    }
    server {
        listen 80;
        server_name lets-go.kotimme.cc;
        location / {
            root /usr/share/nginx/html/lets-go;
            index index.html;
        }
        server_tokens off;
    }
    server {
        listen 80;
        server_name lets-go-further.kotimme.cc;
        location / {
            root /usr/share/nginx/html/lets-go-further;
            index index.html;
        }
        server_tokens off;
    }
}
