# Based on https://medium.com/@nikhil.nagarajappa/installing-influxdb-in-k8s-2fe0e0647431
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  serviceName: "influxdb"
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:2.0.6
        ports:
        - containerPort: 8086
          name: influxdb
        volumeMounts:
        - name: influxdb
          mountPath: /var/lib/influxdb2
          # subPath: influxdb
      volumes:
        - name: influxdb
          nfs:
            server: 192.168.68.150 # IP to our NFS server
            path: /rpool/kubernetes/analytics # The exported directory
            mountPermissions: "1004:1004"
#          persistentVolumeClaim:
#            claimName: influxdb
