---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi
  volumeName: analytics
