# Based on https://medium.com/@nikhil.nagarajappa/installing-influxdb-in-k8s-2fe0e0647431
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  serviceName: "influxdb"
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:latest
        ports:
        - containerPort: 8086
          name: influxdb
        volumeMounts:
        - name: analytics
          mountPath: /var/lib/influxdb2
          subPath: influxdb
      - name: telegraf
        image: telegraf:latest
        ports:
        - containerPort: 9411
          name: telegraf
        volumeMounts:
        - name: analytics
          mountPath: /etc/telegraf
          subPath: telegraf
      volumes:
        - name: analytics
          nfs:
            server: 192.168.68.150 # IP to our NFS server
            path: /rpool/kubernetes/analytics/ # The exported directory
#          persistentVolumeClaim:
#            claimName: influxdb
