# Based on https://medium.com/@nikhil.nagarajappa/installing-influxdb-in-k8s-2fe0e0647431
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  serviceName: "influxdb"
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      securityContext:
        # runAsUser: 
        # runAsGroup: 
        fsGroup: 1004
      containers:
      - name: influxdb
        image: influxdb:2.0.6
        ports:
        - containerPort: 8086
          name: influxdb
        volumeMounts:
        - name: influxdb
          mountPath: /var/lib/influxdb2
          subPath: influxdb
      volumes:
        - name: influxdb
          persistentVolumeClaim:
            claimName: influxdb
