config:
  oidc:
    secret:
      create: false
    externalSecret:
      enabled: true
      name: "oidc-headlamp"
ingress:
  hosts:
  - host: headlamp.kotimme.cc
    paths:
    - path: /
      type: ImplementationSpecific
      backend:
        service:
          name: my-headlamp
          port:
            name: http
  tls:
    - secretName: headlamp-certs
      hosts:
        - headlamp.kotimme.cc
