---
apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb-system
spec:
  local:
    v4pools:
    - subnet: 192.168.80.0/24
      pool: 192.168.80.2-192.168.68.100
      aggregation: default
