---
apiVersion: purelb.io/v2
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb-system
spec:
  local:
    v4pools:
    - subnet: 192.168.80.0/24
      pool: 192.168.80.1-192.168.80.100
      aggregation: default
