---
apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb
spec:
  local:
    v4pools:
    - subnet: 192.168.68.0/24
      pool: 192.168.68.201-192.168.68.220
      aggregation: default
