apiVersion: batch/v1
kind: CronJob
metadata:
  name: certbot
spec:
  schedule: "* * * * 6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: certbot
            image: certbot/dns-cloudflare:latest
            imagePullPolicy: IfNotPresent
            command:
              - certbot
              - renew
              - --config
              - /config-local/certbot/config.ini
            volumeMounts:
              - name: dir
                mountPath: /etc/letsencrypt
                subPath: certbot/etc
              - name: dir
                mountPath: /var/lib/letsencrypt
                subPath: certbot/var-lib
              - name: dir
                mountPath: /config-local/certbot
                subPath: certbot/config
          imagePullSecrets:
            - name: docker-hub
          volumes:
            - name: dir
              persistentVolumeClaim:
                claimName: nfs
          restartPolicy: OnFailure
