# values: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
# apply: helm upgrade --install traefik traefik/traefik --create-namespace --namespace traefik -f helm-customization.yaml


ingressRoute:
  dashboard:
    enabled: true

    # Custom match rule with host domain
    matchRule: "Host(`traefik.kotimme.cc`)"
    entryPoints: ["websecure", "web"]

    # Add custom middlewares : authentication and redirection
    middlewares:
      - name: traefik-dashboard-auth

service:
  spec:
    loadBalancerIP: "192.168.68.250"


additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
