apiVersion: v1
kind: Service
metadata:
  annotations:
    purelb.io/service-group: local
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: my-service
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 6880
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: load-balancer-example
  sessionAffinity: None
  type: LoadBalancer
