# Source: influxdb2/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: influxdb-influxdb2
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8086
  selector:
    app.kubernetes.io/name: influxdb2
    app.kubernetes.io/instance: influxdb
