#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: homepage
#spec:
#  tls:
#  - secretName: homepage-certs
#    hosts:
#    - homepage.kotimme.cc
#  rules:
#  - host: homepage.kotimme.cc
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: homepage
#            port:
#              name: homepage
---
apiVersion: v1
kind: Service
metadata:
    name: redis
spec:
    ports:
      - name: redis
        port: 6379
        targetPort: redis
    selector:
        app: redis
    type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: "redis"
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: homepage.kotimme.cc
        ports:
        - name: redis
          containerPort: 6379
#        volumeMounts:
#        - name: config
#          mountPath: /usr/local/etc/redis/redis.conf
#      imagePullSecrets:
#        - name: ghcr-io
#      volumes:
#        - name: redis
#          configMap:
#            name: app-redis-redis-conf
