namespace: cluster

resources:
# Non-namespaced objects
  - PersistentVolume-cluster.yaml
  - PersistentVolumeClaim.yaml
# Namespaced objects
  - Namespace.yaml
  - Secret-cloudflared.yaml
  - Secret-keycloak.yaml
  - Secret-keycloak-postgres.yaml
  - Secret-kubernetes-dashboard-oauth2-proxy.yaml
  - Secret-kubernetes-dashboard.yaml
  - Secret-traefik.yaml
  - ServiceAccount-admin-user.yaml
# Namespaced apps
  - app-cloudflared.yaml
  - app-keycloak.yaml
  - app-kubernetes-dashboard.yaml
  - app-oauth2-proxy-kubernetes-dashboard.yaml
  - app-portainer.yaml
  - app-redis.yaml
  - app-traefik-dashboard-middleware-certificate.yaml
  - app-traefik.yaml

patches:
  - path: patch-Ingress.yaml
    target:
      kind: Ingress
      
#configMapGenerator:
#  - name: app-redis-redis-conf
#    files:
#      - config/app-redis/redis.conf
