namespace: cluster

resources:
# Non-namespaced objects
  - PersistentVolume-cluster.yaml
# Namespaced objects
  - Namespace.yaml
# Namespaced apps
  - app-kubernetes-dashboard-ClusterRoleBinding.yaml
  - app-kubernetes-dashboard-oauth2-proxy.yaml
  - app-kubernetes-dashboard.yaml
  - app-redis.yaml

#configMapGenerator:
#  - name: app-redis-redis-conf
#    files:
#      - config/app-redis/redis.conf
