[general]
interface=
port=0
enable-transcoding=false
log-level=default:WARNING

[Tracker3]
enabled=false

[MediaExport]
enabled=true
# Update this URL to match your nginx stream service name and path
uris=http://192.168.68.205/radio/YleRadio1Hifi/icecast.audio
title=Yle Radio1 Hifi
