apiVersion: v1
kind: Service
metadata:
  annotations:
    purelb.io/service-group: local
  labels:
    app: portainer-agent
  name: portainer-agent
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: portainer-agent
  sessionAffinity: None
  type: LoadBalancer
