---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: semaphore
spec:
  tls:
  - secretName: semaphore-certs
    hosts:
    - semaphore.kotimme.cc
  rules:
  - host: semaphore.kotimme.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: semaphore
            port:
              name: semaphore
---
apiVersion: v1
kind: Service
metadata:
    name: semaphore
spec:
    ports:
      - name: semaphore
        port: 80
        targetPort: semaphore
    type: ClusterIP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: semaphore
  labels:
    kubernetes.io/service-name: semaphore
addressType: IPv4
ports:
  - name: semaphore
    protocol: TCP
    port: 3000
endpoints:
  - addresses:
      - "192.168.68.109"
    conditions:
      ready: true
