namespace: prod
resources:
  - ../base/
  - ext-app-proxmox-150.yaml

patches:
  - path: patch-PersistentVolumeClaim.yaml
    target:
      kind: PersistentVolumeClaim
  - path: patch-Ingress.yaml
    target:
      kind: Ingress

#transformers:
#  - PrefixSuffixTransformer-host.yaml

#replacements:
#  - path: replacements-hosts.yaml
