namespace: prod
resources:
  - ../base

patches:
  - path: patch-PersistentVolume.yaml
    target:
      kind: PersistentVolume
  - path: patch-PersistentVolumeClaim.yaml
    target:
      kind: PersistentVolumeClaim
