namespace: prod
resources:
  - ../base/

patches:
  - path: patch-PersistentVolumeClaim.yaml
    target:
      kind: PersistentVolumeClaim

transformers:
  - PrefixSuffixTransformer-host.yaml

#replacements:
#  - path: replacements-hosts.yaml
