---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: root
spec:
  tls:
  - secretName: root-certs
    hosts:
    - kotimme.cc
  rules:
  - host: kotimme.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: root
            port:
              name: root

---
# Redirect with domain replacement
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: root-redirect
spec:
  redirectRegex:
    regex: ^https://kotimme/(.*)
    replacement: https://wiki.kotimme/${1}
