---
apiVersion: v1
kind: Service
metadata:
    name: jellyfin
spec:
    ports:
      - name: jellyfin
        port: 8096
        targetPort: 8096
    selector:
        app: jellyfin
    type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  serviceName: "jellyfin"
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        runAsUser: 1978
        runAsGroup: 1978
        fsGroup: 1978
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8096
          name: jellyfin
        volumeMounts:
        - name: config
          mountPath: /config
          subPath: jellyfin/config
        - name: cache
          mountPath: /cache
          subPath: jellyfin/cache
#        - name: media
#          mountPath: /media
#          subPath: jellyfin/cache
      imagePullSecrets:
        - name: docker-hub
      volumes:
        - name: config
          persistentVolumeClaim:
           claimName: nfs
        - name: cache
          persistentVolumeClaim:
           claimName: nfs
#        - name: media
#          nfs:
#           server: 192.168.68.150
#           path: /oricopool/media
