---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default
spec:
  tls:
  - secretName: default-certs
    hosts:
    - '*.kotimme.cc'
  defaultBackend:
    service:
      name: root
      port:
        name: root
