---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-dns
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
  - secretName: default-certs
    hosts:
    - *.kotimme.cc
  defaultBackend:
    service:
      name: grav
      port:
        name: grav
