---
apiVersion: v1
kind: Service
metadata:
    name: mosquitto
spec:
    ports:
      - name: mosquitto
        port: 1883
        targetPort: mosquitto
    selector:
        app: mosquitto
    type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  serviceName: "mosquitto"
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
#      securityContext:
#        runAsUser: 1978
#        runAsGroup: 1978
#        fsGroup: 1978
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: mosquitto
          containerPort: 1883
        volumeMounts:
        - name: dir
          mountPath: /mosquitto
          subPath: mosquitto
#      imagePullSecrets: 
#        - name: ghcr.io
      volumes:
        - name: dir
          persistentVolumeClaim:
           claimName: nfs
