---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grav
spec:
  tls:
  - secretName: grav-certs
    hosts:
    - prod-grav.kotimme.cc
  rules:
  - host: prod-grav.kotimme.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grav
            port:
              name: grav
---
apiVersion: v1
kind: Service
metadata:
    name: grav
spec:
    ports:
      - name: grav
        port: 80
        targetPort: grav
    selector:
        app: grav
    type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grav
  serviceName: "grav"
  template:
    metadata:
      labels:
        app: grav
    spec:
# Cannot be used with Grav
#      securityContext:
#        fsGroup: 1978
      containers:
      - name: grav
        image: truhponen/grav:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grav
          containerPort: 80
        volumeMounts:
        - name: dir
          mountPath: /var/www/html
          subPath: grav
      imagePullSecrets:
        - name: docker-hub
      volumes:
        - name: dir
          persistentVolumeClaim:
           claimName: nfs
