---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grav
spec:
  rules:
# Host will be transformed with Kutomization
  - host: grav
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grav
            port:
              name: grav
---
apiVersion: v1
kind: Service
metadata:
    name: grav
spec:
    ports:
      - name: grav
        port: 80
        targetPort: grav
    selector:
        app: grav
    type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grav
  serviceName: "grav"
  template:
    metadata:
      labels:
        app: grav
    spec:
      securityContext:
        runAsUser: 1978
        runAsGroup: 1978
        fsGroup: 1978
      containers:
      - name: grav
        image: linuxserver/grav:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grav
          containerPort: 80
        volumeMounts:
        - name: dir
          mountPath: /config
          subPath: grav
#      imagePullSecrets: 
#        - name: ghcr.io
      volumes:
        - name: dir
          persistentVolumeClaim:
           claimName: nfs
