
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webkeep
spec:
  tls:
  - secretName: webkeep-certs
    hosts:
    - webkeep.kotimme.cc
  rules:
  - host: webkeep.kotimme.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webkeep
            port:
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: webkeep
  labels:
    app: webkeep
spec:
  ports:
    - name: https
      port: 443
      targetPort: 443
  selector:
    app: webkeep
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webkeep
  labels:
    app: webkeep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webkeep
  serviceName: "webkeep"
  template:
    metadata:
      labels:
        app: webkeep
    spec:
      securityContext:
        fsGroup: 1978
#      imagePullSecrets:
#        - name: docker-hub
      containers:

      - name: webkeep
        image: ghcr.io/keeweb/keeweb:latest 
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: webkeep
        ports:
        - name: https
          containerPort: 443
        volumeMounts:
        - name: pvc-nfs
          mountPath: /config
          subPath: webkeep

      volumes:
        - name: pvc-nfs
          persistentVolumeClaim:
           claimName: nfs
