# Redirect with domain replacement
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-wiki
spec:
  redirectRegex:
    regex: .*
    replacement: https://wiki.kotimme.cc/
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: root
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: prod-redirect-to-wiki@kubernetescrd
spec:
  tls:
  - secretName: root-certs
    hosts:
    - kotimme.cc
  rules:
  - host: kotimme.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grav
            port:
              name: grav
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grav
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: prod-redirect-to-wiki@kubernetescrd
spec:
  tls:
  - secretName: grav-certs
    hosts:
    - grav.kotimme.cc
  rules:
  - host: grav.kotimme.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grav
            port:
              name: grav
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wiki
spec:
  tls:
  - secretName: wiki-certs
    hosts:
    - wiki.kotimme.cc
  rules:
  - host: wiki.kotimme.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grav
            port:
              name: grav
---
apiVersion: v1
kind: Service
metadata:
    name: grav
spec:
    ports:
      - name: grav
        port: 80
        targetPort: grav
    selector:
        app: grav
    type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grav
  serviceName: "grav"
  template:
    metadata:
      labels:
        app: grav
    spec:
# Cannot be used with Grav
#      securityContext:
#        fsGroup: 1978
      containers:
      - name: grav
        image: truhponen/grav:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: grav
          containerPort: 80
        volumeMounts:
        - name: dir
          mountPath: /var/www/html
          subPath: grav
      imagePullSecrets:
        - name: docker-hub
      volumes:
        - name: dir
          persistentVolumeClaim:
           claimName: nfs
