---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: prod-root-redirect@kubernetescrd
spec:
  tls:
  - secretName: default-certs
    hosts:
    - '*.kotimme.cc'
  defaultBackend:
    service:
      name: wiki
      port:
        name: wiki
---
# Redirect with domain replacement
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: root-redirect
spec:
  redirectRegex:
    regex: ^https://kotimme/(.*)
    replacement: https://wiki.kotimme/${1}
