---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-star-certs
spec:
  secretName: root-star-certs
  additionalOutputFormats:
  - type: CombinedPEM
  - type: DER
  dnsNames:
    - 'kotimme.cc'
    - '*.kotimme.cc'
  issuerRef:
    name: cloudflare-dns
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-star-certs-02360-site
spec:
  secretName: root-star-certs
  additionalOutputFormats:
  - type: CombinedPEM
  - type: DER
  dnsNames:
    - '02360.site'
    - '*.02360.site'
  issuerRef:
    name: cloudflare-dns
    kind: ClusterIssuer
    group: cert-manager.io
