---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  annotations:
    ingress.class: "haproxy"
spec:
  rules:
  - host: kube-grafana.kotimme.cc
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 8086

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: influxdb
  annotations:
    ingress.class: "haproxy"
spec:
  rules:
  - host: kube-influxdb.kotimme.cc
    http:
      paths:
      - path: /
        backend:
          serviceName: influxdb
          servicePort: 8086
