resources:
# Non-namespaced objects - not kustomized
  - PersistentVolume-prod.yaml
  - PersistentVolume-qa.yaml
  - PersistentVolume-test.yaml
# Namespaced objects
  - Ingress.yaml
  - Namespace.yaml
  - PersistentVolumeClaim.yaml
  - Secret-docker-hub.yaml
  - Secret-telegraf.yaml
  - app-grafana.yaml
  - app-jellyfin.yaml
  - app-influxdb-telegraf.yaml
