resources:
# Non-namespaced objects - not kustomized
  - PersistentVolume-prod.yaml
  - PersistentVolume-qa.yaml
  - PersistentVolume-test.yaml
# Namespaced objects
  - Namespace.yaml
  - PersistentVolumeClaim.yaml
  - Secret-docker-hub.yaml
  - Secret-technitium.yaml
  - Secret-telegraf.yaml
# Namespaced apps
  - app-filestash.yaml
  - app-grafana.yaml
  - app-grav.yaml
  - app-homeassistant-piper-whisper.yaml
  - app-homepage.yaml
  - app-jellyfin.yaml
  - app-influxdb-telegraf.yaml
  - app-mosquitto.yaml
  - app-musicassistant.yaml
  - app-picard.yaml
  - app-ssh-parser.yaml
  - app-technitium.yaml

configMapGenerator:
  - name: app-ssh-parser-nginx-conf
    files:
      - config/app-ssh-parser/nginx.conf
