resources:
# Non-namespaced objects - not kustomized
  - PersistentVolume-prod.yaml
  - PersistentVolume-qa.yaml
  - PersistentVolume-test.yaml
# Namespaced objects
  - Namespace.yaml
  - PersistentVolumeClaim.yaml
  - Secret-docker-hub.yaml
  - Secret-telegraf.yaml
# Namespaced apps
  - app-filestash.yaml
  - app-grafana.yaml
  - app-grav.yaml
  - app-jellyfin.yaml
  - app-influxdb-telegraf.yaml
  - app-musicassistant.yaml
  - app-technitium.yaml

