resources:
# Non-namespaced objects - not kustomized
  - PersistentVolume-prod.yaml
  - PersistentVolume-qa.yaml
  - PersistentVolume-test.yaml
# Namespaced objects
  - Namespace.yaml
  - Certificate-root-star.yaml
  - PersistentVolumeClaim.yaml
  - Secret-docker-hub.yaml
  - Secret-rss.yaml
  - Secret-stringer.yaml
  - Secret-technitium.yaml
  - Secret-telegraf.yaml
# Namespaced apps
  - app-default.yaml
  - app-excalidraw.yaml
  - app-filestash.yaml
  - app-grafana.yaml
  - app-grav.yaml
  - app-homeassistant-piper-whisper.yaml
  - app-homepage.yaml
  - app-jellyfin.yaml
  - app-influxdb-telegraf.yaml
  - app-mkdocs.yaml
  - app-mosquitto-mqtt-explorer.yaml
  - app-musicassistant.yaml
  - app-nginx.yaml
  - app-picard.yaml
  - app-freshrss.yaml
  - app-stringer.yaml
#  - app-technitium.yaml
  - app-z2m.yaml

configMapGenerator:
  - name: app-nginx-nginx-conf
    files:
      - config/app-nginx/nginx.conf
      - config/app-nginx/mime.types
  - name: app-influxdb-telegraf-telegraf-conf
    files:
      - config/app-influxdb-telegraf/telegraf.conf
