# Using load balance to assign public IP address
---
apiVersion: v1
kind: Service
metadata:
    name: grafana
spec:
    ports:
      - name: grafana
        port: 3000
        targetPort: 3000
    selector:
        app: grafana
    type: NodePort
---
apiVersion: v1
kind: Service
metadata:
    name: influxdb
spec:
    ports:
      - name: influxdb
        port: 8086
        targetPort: 8086
    selector:
        app: influxdb-telegraf
    type: NodePort
