# values: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
# apply: helm upgrade --install traefik traefik/traefik --create-namespace --namespace traefik -f values-traefik.yaml
# create file: helm template traefik traefik/traefik -n cluster -f values-traefik.yaml > app-traefik.yaml


ingressRoute:
  dashboard:
    enabled: true
    
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-dns

    # Custom match rule with host domain
    matchRule: "Host(`traefik.kotimme.cc`)"
    entryPoints: ["websecure"]

    # Add custom middlewares : authentication and redirection
    middlewares:
      - name: traefik-dashboard-auth

    tls:
      secretName: traefik-certs

service:
  spec:
    loadBalancerIP: "192.168.68.250"


additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
