---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
#  nfs:
  csi:
    driver: nfs.csi.k8s.io
    nfs.csi.k8s.io: 192-168-68-150-rpool-kubernetes
    server: 192.168.68.150
    # Each namespace has own NFS share
    path: /rpool/kubernetes
    subDir: ${pvc.metadata.namespace}
