---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automation-nfs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi
  volumeName: nfs
