---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-prod
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.68.150
    path: /rpool/kubernetes/prod
