---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.21
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: automation-nfs
          mountPath: /usr/share/nginx/html
          subPath: nginx
      imagePullSecrets: 
        - name: docker-hub
      volumes:
        - name: automation-nfs
          nfs:
            server: 192.168.68.150 # IP to our NFS server
            path: /rpool/kubernetes/ # The exported directory

