---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  serviceName: "grafana"
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 1978
        runAsGroup: 1978
      containers:
      - name: grafana
        image: grafana/grafana-enterprise:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: GF_SECURITY_ALLOW_EMBEDDING
          value: "true"
        ports:
        - containerPort: 3000
          name: grafana
        volumeMounts:
        - name: grafana
          mountPath: 	/var/lib/grafana
          subPath: grafana
      imagePullSecrets: 
        - name: docker-hub
      volumes:
        - name: grafana
          persistentVolumeClaim:
            claimName: nfs
#      volumes:
#        - name: automation-nfs
#          nfs:
#            server: 192.168.68.150 # IP to our NFS server
#            path: /rpool/kubernetes/ # The exported directory
