# Based on https://medium.com/@nikhil.nagarajappa/installing-influxdb-in-k8s-2fe0e0647431
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb-telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-telegraf
  serviceName: "influxdb-telegraf"
  template:
    metadata:
      labels:
        app: influxdb-telegraf
    spec:
      securityContext:
        runAsUser: 1978
        runAsGroup: 1978
        fsGroup: 1978
      containers:
      # Influxdb container
      - name: influxdb
        image: docker.io/influxdb:2.7.11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8086
          name: influxdb
        volumeMounts:
        - name: influxdb-telegraf
          mountPath: /var/lib/influxdb2
          subPath: influxdb
      # Telegraf MQTT container
      - name: telegraf-mqtt
        image: docker.io/telegraf:1.33.2
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: telegraf
        ports:
        - containerPort: 9411
          name: telegraf-mqtt
        volumeMounts:
        - name: influxdb-telegraf
          mountPath: /etc/telegraf
          subPath: telegraf-mqtt
      imagePullSecrets:
        - name: docker-hub
  volumeClaimTemplates:
  - metadata:
      name: influxdb-telegraf
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 10Gi
      storageClassName: 'nfs-csi'
#  - metadata:
#      name: influxdb
#    spec:
#      accessModes: [ "ReadWriteMany" ]
#      resources:
#        requests:
#          storage: 10Gi
#      storageClassName: 'nfs-csi'
