namespace: whitelabel

resources:
# Non-namespaced objects
  - PersistentVolume-whitelabel.yaml
# Namespaced objects
  - PersistentVolumeClaim.yaml
  - Namespace.yaml
  - Secret-mysql.yaml
# Namespaced apps
  - app-mysql.yaml
#  - app-snippetbox.yaml

#configMapGenerator:
#  - name: app-redis-redis-conf
#    files:
#      - config/app-redis/redis.conf
