namespace: qa
namePrefix: kube-
resources:
  - ../base/

patches:
  - path: patch-PersistentVolumeClaim.yaml
    target:
      kind: PersistentVolumeClaim

transformers:
  - host-prefix-transformer.yaml
