---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-qa
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 192-168-68-150-rpool-kubernetes-qa
    volumeAttributes:
      server: 192.168.68.150
      # Each namespace has own NFS share
      share: /rpool/kubernetes/qa
#      subDir: ${pvc.metadata.namespace}
